# Generated by Django 4.2.13 on 2024-05-27 15:21

import MathInfo_Academy.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('laboratory', 'Laboratory')], default='lecture', max_length=10)),
                ('max_grade', models.FloatField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.user')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.FloatField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.user')),
                ('teacher_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.teacher_activity')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documentation', models.FileField(upload_to=MathInfo_Academy.models.documentation_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('teacher_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.teacher_activity')),
            ],
        ),
    ]
