# Generated by Django 5.0.2 on 2024-02-21 15:24

import MathInfo_Academy.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract_Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('no_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_even', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('laboratory', 'Laboratory')], default='lecture', max_length=10)),
                ('abstract_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.abstract_subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(to='MathInfo_Academy.group')),
                ('interval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.interval')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.room')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Subject_Concrete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('documentation', models.FileField(upload_to=MathInfo_Academy.models.documentation_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('teacher_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.teacher_subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('teachers_subjects_concrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MathInfo_Academy.teacher_subject_concrete')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.group')),
            ],
        ),
        migrations.AddField(
            model_name='teacher_subject_concrete',
            name='students_present_concrete',
            field=models.ManyToManyField(through='MathInfo_Academy.Student_Attendance', to='MathInfo_Academy.user'),
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='students_optionals',
            field=models.ManyToManyField(related_name='students_optionals', to='MathInfo_Academy.user'),
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.user'),
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MathInfo_Academy.user'),
        ),
        migrations.AddField(
            model_name='teacher_subject_concrete',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MathInfo_Academy.week'),
        ),
        migrations.AddField(
            model_name='teacher_subject',
            name='week',
            field=models.ManyToManyField(through='MathInfo_Academy.Teacher_Subject_Concrete', to='MathInfo_Academy.week'),
        ),
    ]
