# Generated by Django 4.2.13 on 2024-06-04 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MathInfo_Academy', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='teacher_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MathInfo_Academy.teacher_activity'),
        ),
        migrations.AlterField(
            model_name='students_activity',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students_activity',
            name='teacher_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MathInfo_Academy.teacher_activity'),
        ),
        migrations.AlterField(
            model_name='teacher_activity',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MathInfo_Academy.subject'),
        ),
        migrations.AlterField(
            model_name='teacher_activity',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
