version: '3'
services:
  db:
    image: mysql:8.0.36
    volumes:
      - app_licenta_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"

volumes:
  app_licenta_vol: